version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Port-Mapping: Host-Port 8080 zu Container-Port 80
    volumes:
      - ./html:/usr/share/nginx/html  # Bindet das lokale Verzeichnis 'html' zum Nginx-HTML-Root im Container

